# R packages -- "bigdatapackages2017.R"
# for standard install on RStudio Server and
# on lab computers

install.packages("tidyverse") # installs numerous other
#    packages, including ggplot2, dplyr, tidyr,readr, purrr, tibble.

install.packages("AppliedPredictiveModeling")
install.packages("arules")
install.packages("arulesViz")
install.packages("car")
install.packages("caret", dependencies = c("Depends", "Suggests"))
install.packages("corrplot")
install.packages("crosstalk")
install.package("e1071")
install.packages("ElemStatLearn")
install.packages("gapminder")
install.packages("gcookbook")
install.packages("ggmap")
install.packages("ggvis")
install.packages("googleVis")
install.packages("hflights")
install.packages("igraph")
install.packages("knitr")
install.packages("leaflet")
install.packages("lubridate")
install.packages("magrittr")
install.packages("manipulate")
install.packages("maps")
install.packages("mclust")
install.packages("mdsr")
install.packages("mosaic")
install.packages("mosaicData")
install.packages("nnet")
install.packages("party")
install.packages("plotly")
install.packages("randomForest")
install.packages("RColorBrewer")
install.packages("RCurl")
install.packages("reshape2")
install.packages("rggobi")
install.packages("rmarkdown")
install.packages("ROCR")
install.packages("rpart.plot")
install.packages("rpart")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("SnowballC")
install.packages("titanic")
install.packages("tm")
install.packages("WDI")
install.packages("wordcloud")

# Especially for BUS256 Marketing Analytics

install.packages("ChoiceModelR")
install.packages("gam")
install.packages("quantmod")
install.packages("Quandl")
install.packages("support.CEs")
install.packages("vcd")
install.packages("XML")
install.packages("xts")
install.packages("zoo")
